### ISSUE TITLE
Webhook support

### ISSUE THREAD

**Issue by WyriHaximus** [cebe/php-openapi#114]
I'm aware of #101 but wanted to file this separately since it's a new feature and not a spec upgrade. [OAS 3.1 supports webhooks](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#oasWebhooks). Would you be open to a PR adding that, and if so give me some pointers so I can start working on that?

**Comment by cebe** [comment]
I have not taken a look into what exactly needs to be changed to support OAS 3.1, but somehow spec objects need to know which version of the spec they are representing and based on that enable the new feature.

If you want to work on that, I am happy to receive a PR.

**Comment by WyriHaximus** [comment]
Ok awesome will have a go at it. Already using this package to parse a spec with webhooks, but having webhook support in here will also enable using a validator to pick the correct entity from the webhook call :tada:

**Comment by WyriHaximus** [comment]
Opened #115 as WIP to add this, probably also contains some changes that handle the 3.0 vs 3.1 detections + the 3.1 spec files

**Comment by shulard** [comment]
Hey !

Since #115 has been merged, should we close this one ?

**Comment by WyriHaximus** [comment]
Yup, been able to use it with webhooks for some time now :+1:
