### ISSUE TITLE
Error: Call to a member function resolveReferences() on array

### ISSUE THREAD

**Issue by garak** [cebe/php-openapi#119]
Method [resolverReferences](https://github.com/cebe/php-openapi/blob/master/src/spec/Responses.php#L238) is calling `resolveReferences` method on `$referencedObject` without checking if it's an array, resulting in the error mentioned in issue object.
The `$referencedObject` variable is suggested via phpdoc to be `Response|Reference|null`, but `resolve` method can return an array.

**Comment by oxoTHuk89** [comment]
Agree ++
