### ISSUE TITLE
Improve resolving references, cache loaded files in current context

### ISSUE THREAD

**Issue by cebe** [cebe/php-openapi#13]
To avoid multiple requests to the same file, loaded files can be cached in current context.

**Comment by cebe** [comment]
https://github.com/cebe/php-openapi/blob/4a4892dbee51d9578b72d6c42645b5e89473d252/src/spec/Reference.php#L107

**Comment by coatesap** [comment]
I have a feeling this lack of caching is the biggest performance burden when reading API files. As an experiment, I ran [Speccy's resolve command](https://github.com/wework/speccy#resolve-command) over my API file first (which took ~1 sec). Using the resolved output from Speccy dropped the time of `Reader::readFromYamlFile()` down from 24 seconds to 10 seconds, which is fairly significant.
