### ISSUE TITLE
Symfony 6 support

### ISSUE THREAD

**Issue by jokaorgua** [cebe/php-openapi#148]
Would be nice to get a symfony 6 support. I guest no huge changes were made from symfony 5 (which is supported) to symfony 6. So it will be enough just to change the composer.json

**Comment by jokaorgua** [comment]
https://github.com/cebe/php-openapi/pull/134

found support in this PR. merge it please

**Comment by cebe** [comment]
done. php-openapi 1.6.0 now supports symfony 6
