### ISSUE TITLE
getErrors falls in infinite recursion

### ISSUE THREAD

**Issue by sprymiker** [cebe/php-openapi#16]
What: Bug
Severity: 1

How to reproduce:
Use the scheme with cyclic references

The result:
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 262144 bytes) in .../vendor/cebe/php-openapi/src/SpecBaseObject.php on line 161

**Comment by cebe** [comment]
Hi, thanks for the report. Could you please provide an example spec that produces the error?

**Comment by cebe** [comment]
@sprymiker do you have any feedback about this issue?

**Comment by cebe** [comment]
unable to reproduce.
