### ISSUE TITLE
Add support for symfony/yaml version ^7

### ISSUE THREAD

**Issue by ovidiuenache** [cebe/php-openapi#200]
There have been some talks about removing this dependency from the list of required packages and there is an issue created regarding this (https://github.com/cebe/php-openapi/issues/170). However, there has been no update on it and I believe we should either remove it or keep it updated. This issue is focusing on the latter.

I'll open a PR about this.

**Comment by ovidiuenache** [comment]
https://github.com/cebe/php-openapi/pull/202

**Comment by ovidiuenache** [comment]
cc @cebe

**Comment by tacman** [comment]
Hi @cebe thanks for putting this library together.  Any chance you could approve allowing the Symfony 7 YAML parser?  

If you are going to release a new version, you could even just support php 8.1+ and Symfony 6/7.

**Comment by cebe** [comment]
#212 is merged with symfony 7 support.

**Comment by tacman** [comment]
thanks!  Given how tiny the change is, can you tag it as a 1.7.1 release?  (1.7.0 was in 2022)
