### ISSUE TITLE
Wrong type hint for some properties

### ISSUE THREAD

**Issue by jdomenechb** [cebe/php-openapi#34]
As an example, in class `Operation`, `requestBody` property is defined as:

https://github.com/cebe/php-openapi/blob/13b91759f9daccd90729e1c246bab791f13e59c8/src/spec/Operation.php#L23

However, if the `requestBody` property is NOT in the contract, getting the property results in `null`. Therefore, the type hint should be updated to reflect that.

This might happen with other properties in the same or other objects: what I've just posted is an example.

**Comment by cebe** [comment]
Fixed, thanks for reporting!
