### ISSUE TITLE
Any chance of using a different version of Symfony YAML?

### ISSUE THREAD

**Issue by keisetsu** [cebe/php-openapi#35]
My project uses Symfony 3.4, and we're not likely to update to 4 any time soon. Do you need features from 4.0?

Ideally you could use a non-symfony library, but I don't know what the prospects are for that.

**Comment by yya** [comment]
Same issue for me. Is there any chance to add support for symfony/yaml >= 3.0 as well? Thnx

**Comment by cebe** [comment]
As far as I remember the interface changed in 4.0, so I pinned the version to make sure it works, will look into that.

Also there is the option in using another library, but it seems the symfony one is the best option available right now (#21).

**Comment by cebe** [comment]
https://github.com/symfony/symfony/issues/27965#issuecomment-535043620

**Comment by cebe** [comment]
Updated composer.json, with the release of version 1.3 (probably going to happen tomorrow) you should be able to use this lib with symfony 3 and symfony 4.
