### ISSUE TITLE
Empty security array incorrectly converted to empty object (YAML)

### ISSUE THREAD

**Issue by coatesap** [cebe/php-openapi#52]
When using `$schema = Reader::readFromYaml($content)` followed by `Writer::writeToYaml($schema)` any instances of `security: []` are incorrectly converted to `security: { }`. This is invalid (it should remain as an empty array) and causes any tooling that reads the newly written spec to fall over.

**Comment by coatesap** [comment]
It looks like the fix for this would probably be to change line 37 of Writer.php from:

```php
return Yaml::dump($object->getSerializableData(), 256, 2, Yaml::DUMP_OBJECT_AS_MAP);
```

to

```php
return Yaml::dump($object->getSerializableData(), 256, 2, Yaml::DUMP_OBJECT_AS_MAP | Yaml::DUMP_EMPTY_ARRAY_AS_SEQUENCE);
```

This may well also fix #46

**Comment by cebe** [comment]
https://github.com/OAI/OpenAPI-Specification/pull/1886

**Comment by coatesap** [comment]
Hi @cebe - does my suggestion above seem sensible, or are there any other considerations that need to be taken into account? If it looks ok, I'm happy to test it and open a PR...

**Comment by cebe** [comment]
if there is no valid case where an empty object needs to represent something else, we can apply this change.
