### ISSUE TITLE
Can't install on Symfony 4.4

### ISSUE THREAD

**Issue by recchia** [cebe/php-openapi#60]
The allowed symfony versions are: ^3.0 | ~4.0.0 | ~4.1.0 | ~4.2.0 | ~4.3.0 | ^5.0 but not 4.4, this is a transition version to 5. In 4.4 you can fix/remove deprecated code before migrate to version 5

**Comment by cebe** [comment]
I explicitly disallowed 4.4 because of this bug:  symfony/symfony#34805

**Comment by recchia** [comment]
Ok i didn't know, thanks for your response
