### ISSUE TITLE
Add option to inline only external references

### ISSUE THREAD

**Issue by cebe** [cebe/php-openapi#63]
Currently resolving references resolves all references unless they are recursive.

There should be more options to support cases where only external references should be inlined.
See also:
https://stoplight.io/blog/keeping-openapi-dry-and-portable/

**Comment by aedart** [comment]
Is there any way that this can be achieved in the current released version? If so, could you please point in the right direction?

**Comment by cebe** [comment]
It will be possible with release of version 1.5, on master you can use $resolveReferences parameter of `readFromJsonFile()` and `readFromYamlFile()`:

https://github.com/cebe/php-openapi/blob/015bd48b0f963e65641a33ce9c333e62d6ad8ee3/src/Reader.php#L64-L66

**Comment by cebe** [comment]
- [ ] should be implemented in the command line tool:

  https://github.com/cebe/php-openapi/blob/34f6e203e2fc16e570dd280487d42e1296c0e4d2/bin/php-openapi#L192-L194

- [ ] docs need to be added to the README

**Comment by cebe** [comment]
1.5.0 is going to be released today.
