### ISSUE TITLE
Move to symfony console

### ISSUE THREAD

**Issue by vladyslavstartsev** [cebe/php-openapi#64]
I think it will be easier to manage things if you move to symfony console (with is de-facto standard for the console apps in php).

**Comment by cebe** [comment]
what exactly is easier? It will add another dependency on a symfony component, making it harder to use the library with different symfony versions.

**Comment by vladyslavstartsev** [comment]
1) this file will https://github.com/cebe/php-openapi/blob/master/bin/php-openapi
will look OO way
2) you can do the same thing as you did with `symfony/yaml`
https://github.com/cebe/php-openapi/blob/98fedafe3827188610564dee18e4d09ab08ddbbb/composer.json#L23

**Comment by TroodoNmike** [comment]
I also think this is good idea. It would help collaborate on the same command format like in other php applications. At the moment bin/php-openapi looks like its trying to re-invent the wheel. I know it looks small and simple but it probably does not handle many edge cases. Please dont take it as a must thing from my side, its just a recommendation. Here is component documentation https://symfony.com/doc/current/components/console.html

**Comment by cebe** [comment]
> you can do the same thing as you did with `symfony/yaml`

such a strategy would require symfony console API to be stable among major versions. This works quite okay for Yaml as there are only two method calls relevant for us. Symfony consoles API is much more complex and might introduce breaking changes making it hard to adapt to new symfony versions. This package should be installable regardless of the Symfony version so I will not add another dependency that can cause problems with breaking changes.
