### ISSUE TITLE
Get request / response model definition from specifications

### ISSUE THREAD

**Issue by Neirda24** [cebe/php-openapi#66]
I think it would be great to have some kind of "finder" to retrieve the model as associative array based on parameters.

For Request body we need :

- a concrete URI
- an http method

For Responses we need :

- a concrete URI
- an http method
- a status code
- content-type

It could be usefull in PHPUnit for example to retrieve the specific model and test it against jsonschema validator.

**Comment by cebe** [comment]
Not sure I understand what you are trying to do. Can you give an example function call and what you expect it to return?

**Comment by cebe** [comment]
No answer :arrow_right: closing. Happy to reopen if you explain in more detail.
