### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by canvural** [cebe/php-openapi#81]
Hello,

Are there any plans for adding support for PHP 8?

Today I checked what needs to be updated. All dependencies except `php-cs-fixer` have PHP 8 compatible versions. So the issues I found are:
1. `php-cs-fixer` needs to updated. There is an [issue](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4702) about it there. Looks like it's still a work in progress. But as mentioned in the discussion [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4702#issuecomment-719545818), it is not really a blocker. PHAR release can be downloaded and used in CI. Or something like https://github.com/bamarni/composer-bin-plugin

2. Some PHPUnit methods used in tests are deprecated in newer versions. But that's easy to fix I guess.

What are your thoughts?

**Comment by cebe** [comment]
> Are there any plans for adding support for PHP 8?

sure :)

**Comment by canvural** [comment]
Ok. So, looking forward to it :+1:
