### ISSUE TITLE
Recursion bug

### ISSUE THREAD

**Issue by Insolita** [cebe/php-openapi#85]
lint failed with an error that not enough memory

**Comment by Insolita** [comment]
Minimal example with bug  https://gist.github.com/Insolita/2cc4480668cff5dd4c48859328969297

**Comment by cebe** [comment]
> Minimal example for reproduce bug https://gist.github.com/Insolita/2cc4480668cff5dd4c48859328969297

Putting that YAML into `recursion.yaml` works for me:
```
$ php -dmemory_limit=64M  bin/php-openapi validate recursion.yaml
The supplied API Description validates against the OpenAPI v3.0 schema.
```

need more information to reproduce the issue.
